# Generated by Django 5.0.4 on 2024-04-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_payment_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Chấp nhận', 'Chấp nhận'), ('Đóng gói', 'Đóng gói'), ('Đang giao hàng', 'Đang giao hàng'), ('Đã giao hàng', 'Đã giao hàng'), ('Hủy', 'Hủy'), ('Chờ xử lý', 'Chờ xử lý')], default='Pending', max_length=50),
        ),
    ]
