# Generated by Django 5.0.4 on 2024-04-14 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_razorpay_order_id_payment_stripe_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
