# Generated by Django 5.0.4 on 2024-05-15 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
